//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BenchPro.rc
//
#define ID_READ_PWR_M3_VALUE            3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BenchProTYPE                130
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_CONNECT              310
#define IDD_DIALOG_CONNECT_ADD          312
#define IDD_DIALOG_CONNECT_DEVIDECONNCET 314
#define IDD_DIALOG_DEVIDE_SETTING       316
#define IDD_DIALOG_DEVICE_SELECT        318
#define IDD_DIALOG_POWER_CHANEL         320
#define IDR_MENU1                       321
#define IDR_MENU_PIN_SETTING_EDIT       321
#define IDB_BITMAP_SELECT               323
#define IDD_DIALOG_DEVICE_PROPERTIES    324
#define IDD_DIALOG_DEVICE_JACK          326
#define IDD_DIALOG_DEVICE_JACK_NAME     328
#define IDD_DIALOG_DEVICE_JACK_PROPERTIES 330
#define IDD_DIALOG_DEVICE_JACK_PROPERTIES_EDIT 332
#define IDD_DIALOG_PIN_SETTING          338
#define IDB_IMAGES                      342
#define IDR_MENU2                       343
#define IDD_DIALOG_PIN_SETTING_ADD      344
#define IDD_DIALOG_PIN_SETTING_EDIT     346
#define IDD_DIALOG_PLAN_FILE_CONFIG     348
#define IDB_BITMAP_OFF                  352
#define IDB_BITMAP_ON                   353
#define IDD_DIALOG_POWER_SETTING        354
#define IDD_DIALOG_POWER_SETTING_THRESHOLd 356
#define IDD_DIALOG_POWER_SETTING_PARAM  358
#define IDD_DIALOG_CREATE_TESTCASE      360
#define IDD_DIALOG_CHANEL_SELECTION     362
#define IDR_MENU_CHANEL_SELECTION       364
#define IDB_BMP_ONOFNM                  365
#define IDD_DLG_TESTONBOARD             366
#define IDD_DLGMAIN                     368
#define IDD_DIALOG_CHANEL_ONOFF         370
#define IDD_DIAG_PASSWORD               372
#define IDC_LIST_CONNECT                1000
#define IDC_BUTTON_ADD                  1001
#define IDC_BUTTON_EDIT                 1002
#define IDC_BUTTON_VERIFY               1003
#define IDC_BUTTON_REMOVE               1004
#define IDC_EDIT1                       1005
#define IDC_EDIT_DEVIDE_NAME            1005
#define IDC_EDIT_ADDRESS                1005
#define IDC_EDIT_NAME                   1005
#define IDC_EDIT_SYMBOL                 1005
#define IDC_EDIT_NPIN                   1005
#define IDC_EDIT_USET_P1                1005
#define IDC_EDIT_IMAX_3V3               1005
#define IDC_EDIT_V_Hi_LOGIC_OUT         1005
#define IDC_EDIT_DEVICE_NAME            1005
#define IDC_EDIT_DEVICENAME             1005
#define IDC_EDIT_USERNAME               1005
#define IDC_EDIT_JACK_SIGN              1005
#define IDC_EDIT_STATUS_CONNECT         1005
#define IDC_EDIT_PASSWORD               1005
#define IDC_EDIT_DEVIDE_PORT            1006
#define IDC_EDIT_V_CMP_LOGIC_IN         1006
#define IDC_EDIT3                       1007
#define IDC_EDIT_LOCAL_PORT             1007
#define IDC_EDIT_RESULT                 1007
#define IDC_EDIT_PWP                    1007
#define IDC_EDIT_POWER                  1007
#define IDC_EDIT_USET_P4                1007
#define IDC_EDIT_IMAX_12V               1007
#define IDC_EDIT_HIVOLTAGE_OUT1         1007
#define IDC_TESTCASE_INFO               1007
#define IDC_EDIT_HV_OUT1                1007
#define IDC_EDIT_BAI                    1007
#define IDC_EDIT_IDJACK                 1007
#define IDC_EDIT_USERNAME2              1007
#define IDC_EDIT_VER                    1007
#define IDC_IPADDRESS_DEVIDE            1008
#define IDC_EDIT_HIVOLTAGE_OUT2         1008
#define IDC_EDIT_HV_OUT2                1008
#define IDC_EDIT_TIMEOUT                1009
#define IDC_EDIT_HIVOLTAGE_IN1          1009
#define IDC_EDIT_HV_IN1                 1009
#define IDC_LIST_DEVIDE                 1010
#define IDC_DEVIDE_LIST_CTRL            1010
#define IDC_EDIT_HIVOLTAGE_IN2          1010
#define IDC_EDIT_HV_IN2                 1010
#define IDC_DEVICE_LIST                 1014
#define IDC_BTN_SELECTION               1015
#define IDC_BTN_ADD                     1016
#define IDC_BTN_REMOVE                  1017
#define IDC_CUSTOM1                     1018
#define IDC_GRID                        1018
#define IDC_CST_GRID                    1018
#define IDC_EDIT_CHANEL                 1019
#define IDC_EDIT_PWN                    1020
#define IDC_LIST_CRTL                   1021
#define IDC_EDIT_JACK_NAME              1025
#define IDC_LIST_CTRL                   1026
#define IDC_COMBO_BOARD                 1048
#define IDC_COMBO2                      1049
#define IDC_COMBO_POWER                 1049
#define IDC_COMBO_VALUE_ADC2            1049
#define IDC_EDIT_BOARD                  1051
#define IDC_BUTTON_CONFIG_PLAN          1056
#define IDC_BUTTON_SAVE_AS_CONFIG_FILE  1057
#define IDC_BUTTON_SET                  1058
#define IDC_BTN_P1_ON_OFF               1061
#define IDC_BTN_P2_ON_OFF               1065
#define IDC_BTN_P3_ON_OFF               1068
#define IDC_BTN_P4_ON_OFF               1071
#define IDC_BTN_P5_ON_OFF               1074
#define IDC_BTN_P6_ON_OFF               1077
#define IDC_BTN_P7_ON_OFF               1080
#define IDC_BTN_P8_ON_OFF               1083
#define IDC_BUTTON_GET                  1084
#define IDC_BUTTON_SEND                 1085
#define IDC_EDIT_USET_P2                1087
#define IDC_EDIT_USET_P3                1088
#define IDC_EDIT_UGET1                  1096
#define IDC_EDIT_UGET2                  1097
#define IDC_EDIT_UGET3                  1098
#define IDC_EDIT_UGET4                  1099
#define IDC_EDIT_USET_P5                1100
#define IDC_EDIT_USET_P6                1101
#define IDC_EDIT_USET_P7                1102
#define IDC_EDIT_UGET5                  1103
#define IDC_EDIT_UGET6                  1104
#define IDC_EDIT_UGET7                  1105
#define IDC_EDIT_IMAXSET1               1106
#define IDC_EDIT_IMAXSET2               1107
#define IDC_EDIT_IMAXSET3               1108
#define IDC_EDIT_IMAXSET4               1109
#define IDC_EDIT_IMAXSET6               1110
#define IDC_EDIT_IMAXSET7               1111
#define IDC_EDIT_IMAXSET8               1112
#define IDC_EDIT_IGET1                  1113
#define IDC_EDIT_IGET2                  1114
#define IDC_EDIT_IGET3                  1115
#define IDC_EDIT_IGET4                  1116
#define IDC_EDIT_IGET6                  1117
#define IDC_EDIT_IGET7                  1118
#define IDC_EDIT_IGET8                  1119
#define IDC_EDIT_USET_P8                1122
#define IDC_EDIT_UGET8                  1123
#define IDC_EDIT_IMAXSET5               1124
#define IDC_EDIT_IGET5                  1125
#define IDC_EDIT2                       1127
#define IDC_EDIT_IMAX_5V                1127
#define IDC_EDIT_ADC1                   1127
#define IDC_EDIT_BOARD_NAME             1127
#define IDC_EDIT_TEST                   1127
#define IDC_EDIT_MAIN_TITLE             1127
#define IDC_EDIT_MAIN_TITLE_U           1127
#define IDC_EDIT_ID_JACK                1127
#define IDC_EDIT4                       1128
#define IDC_EDIT_IMAX_12V_N             1128
#define IDC_EDIT_ADC2                   1128
#define IDC_EDIT_TEST_I                 1128
#define IDC_EDIT_CHANEL_ID_JACK         1128
#define IDC_EDIT5                       1129
#define IDC_EDIT_IMAX_12V_ROLE          1129
#define IDC_EDIT_DAC1                   1129
#define IDC_EDIT_MAIN_TITLE_ONPENTESTCASE 1129
#define IDC_EDIT6                       1130
#define IDC_EDIT_IMAX_30V               1130
#define IDC_EDIT_DAC2                   1130
#define IDC_EDIT_TENDAI                 1130
#define IDC_EDIT7                       1131
#define IDC_EDIT_U12V_DOWN              1131
#define IDC_EDIT_IOEXT_1                1131
#define IDC_EDIT_TENBOMACH              1131
#define IDC_EDIT8                       1132
#define IDC_EDIT_U30V_DOWN              1132
#define IDC_EDIT_IOEXT_2                1132
#define IDC_EDIT_TENBAIKT               1132
#define IDC_EDIT9                       1133
#define IDC_EDIT_U12V_UP                1133
#define IDC_EDIT_TITLE                  1133
#define IDC_EDIT10                      1134
#define IDC_EDIT_U30V_UP                1134
#define IDC_BUTTON_ENABLE_BOARD         1137
#define IDEXIT                          1138
#define IDC_BUTTON_SETPIN_CHANEL        1139
#define IDC_BUTTON_SET_PATH             1140
#define IDC_BUTTON_RESET_PATH           1141
#define IDC_EDIT_IMAX_12V_CPU           1142
#define IDC_BTN_SET                     1143
#define IDC_BMP_IMAX_3V3                1145
#define IDC_OPEN_TESTCASE               1146
#define IDC_BMP_IMAX_5V                 1146
#define IDC_STATIC_DEVICE_NAME          1147
#define IDC_BMP_IMAX_12V                1147
#define IDC_STATIC_BOARD_NAME           1148
#define IDC_BMP_IMAX_12V_N              1148
#define IDC_COMBO_TESTCASEi             1149
#define IDC_BMP_IMAX_12V_CPU            1149
#define IDC_BMP_IMAX_12V_ROLE           1150
#define IDC_BMP_IMAX_30V                1151
#define IDC_BMP_UGET1                   1159
#define IDC_BMP_UGET2                   1160
#define IDC_BMP_V_Hi_LOGIC_OUT          1160
#define IDC_BMP_UGET3                   1161
#define IDC_BMP_V_CMP_LOGIC_IN          1161
#define IDC_BMP_UGET4                   1162
#define IDC_BMP_HIVOLTAGE_OUT1          1162
#define IDC_BMP_U12V_DOWN               1162
#define IDC_BMP_HV_OUT1                 1162
#define IDC_BMP_UGET5                   1163
#define IDC_BMP_HIVOLTAGE_OUT2          1163
#define IDC_BMP_U30V_DOWN               1163
#define IDC_BMP_HV_OUT2                 1163
#define IDC_BMP_UGET6                   1164
#define IDC_BMP_HIVOLTAGE_IN1           1164
#define IDC_BMP_U12V_UP                 1164
#define IDC_BMP_HV_IN1                  1164
#define IDC_BMP_UGET7                   1165
#define IDC_BMP_HIVOLTAGE_IN2           1165
#define IDC_BMP_U30V_UP                 1165
#define IDC_BMP_HV_IN2                  1165
#define IDC_BMP_UGET8                   1166
#define IDC_BMP_ADC1                    1166
#define IDC_BTN_EDIT_TESTCASE           1166
#define IDC_BMP_IGET1                   1167
#define IDC_BMP_ADC2                    1167
#define IDC_BTN_SAVE                    1167
#define IDC_BMP_IGET2                   1168
#define IDC_BMP_DAC1                    1168
#define IDC_BMP_IGET3                   1169
#define IDC_BMP_DAC2                    1169
#define IDC_BMP_IGET4                   1170
#define IDC_BMP_IGET5                   1171
#define IDC_BMP_IGET6                   1172
#define IDC_BMP_IGET7                   1173
#define IDC_BMP_IGET8                   1174
#define IDC_SAVE                        1175
#define IDC_BTTN_SAVE                   1177
#define IDC_EDIT_HV_OUT1_name           1178
#define IDC_EDIT_HV_OUT2_name           1179
#define IDC_EDIT_HV_IN1_name            1180
#define IDC_EDIT_HV_IN2_name            1181
#define IDC_EDIT_IOEXT_1_name           1182
#define IDC_EDIT_IOEXT_2_name           1183
#define IDC_EDIT_ADC1_name              1186
#define IDC_EDIT_ADC2_name              1187
#define IDC_EDIT_DAC1_name              1188
#define IDC_EDIT_DAC2_name              1189
#define IDC_EDIT_V_Hi_LOGIC_OUT_name    1190
#define IDC_EDIT_V_CMP_LOGIC_IN_name    1191
#define IDC_COMBO_ADC1                  1198
#define IDC_COMBO_ADC2                  1199
#define IDC_COMBO_DAC1                  1200
#define IDC_COMBO_DAC2                  1201
#define IDC_CHECK_HV_OUT1               1202
#define IDC_CHECK_HV_OUT2               1203
#define IDC_CHECK_HV_IN1                1204
#define IDC_CHECK_HV_IN2                1205
#define IDC_CHECK_EDIT_ADC1             1210
#define IDC_CHECK_ADC2                  1211
#define IDC_CHECK_DAC1                  1212
#define IDC_CHECK_DAC2                  1213
#define IDC_BMP_IOEXT_1                 1214
#define IDC_BMP_IOEXT_2                 1215
#define IDC_BMP1                        1218
#define IDC_BMP2                        1219
#define IDC_BMP3                        1220
#define IDC_BMP4                        1221
#define IDC_BMP5                        1222
#define IDC_BMP6                        1223
#define IDC_BMP7                        1224
#define IDC_BMP8                        1225
#define IDC_BMP9                        1226
#define IDC_BMP10                       1227
#define IDC_BMP11                       1228
#define IDC_BMP12                       1229
#define IDC_BMP13                       1230
#define IDC_BMP14                       1231
#define IDC_BUTTON1                     1233
#define IDC_BTN_SENDTOTHANH             1233
#define IDC_BTN1                        1233
#define IDC_BTN_Connect                 1233
#define IDC_BTN_EXIT                    1233
#define IDC_BTN_SUA                     1233
#define IDC_BTN_EDIT                    1233
#define IDC_BTN2                        1234
#define IDC_BTN_EXIT2                   1234
#define IDC_BTN3                        1235
#define IDC_BTN4                        1236
#define IDC_BTN5                        1237
#define IDC_BTN6                        1238
#define IDC_BTN7                        1239
#define IDC_BTN8                        1240
#define IDC_BTN_CREATECASE              1241
#define IDC_BTN_POWERSETTING            1242
#define IDC_BTN_POWERTHRESHOL           1243
#define IDC_BTN_PIN_SETTING             1244
#define IDC_BTN_PIN_SELECTION           1246
#define IDC_BTN_EXTRA_SETTING           1247
#define IDC_BTN_CREATE_DATA_TESTCASE    1248
#define IDC_BTN_RECONNECT               1249
#define IDC_BTN_POWER_SETTING           1250
#define IDC_BTN_POWER_THRESHOL          1251
#define IDC_BTN_PINSELECT               1252
#define IDC_BTN_POWER_PARA_EXTR         1254
#define IDC_BUTTON2                     1255
#define IDC_BTN_RUNASUSER               1255
#define IDC_BTN_THOAT                   1255
#define IDC_BTN_RESET_PATH              1255
#define IDC_BTN_KT_CN                   1256
#define IDC_STATIC_MACH_PIC             1257
#define IDC_BTN_RESET                   1259
#define IDC_PROGRESS1                   1260
#define IDC_PROGRESS                    1260
#define IDC_RADIO1                      1265
#define IDC_RADIO2                      1266
#define IDC_EDIT11                      1268
#define IDC_EDIT_MAIN_TITLE_TL1         1268
#define IDC_COMBO1                      1269
#define IDC_CMB_ID_JACK                 1269
#define IDC_COMBO_VALUE_ADC1            1269
#define ID_FILE_LOGIN                   32771
#define ID_FILE_FILE                    32772
#define ID_CONNECTTODEVIDE              32773
#define ID_DEVIDESETTING                32774
#define ID_POWERSETTING                 32775
#define ID_POW                          32776
#define ID_POWERSELECTION               32777
#define ID_TOOLS_CHANELSELECTION        32778
#define ID_CHANELSETTING                32779
#define ID_TOOLS_LOGICTEST              32780
#define ID_LOGICTEST                    32781
#define ID_TOOLS_CONNECTTODEVIDE        32782
#define ID_TOOLS_POWERSELECTION         32785
#define ID_TOOLS_CHANELSETTING          32786
#define ID_TOOLS_PINSETTING             32792
#define ID_PIN_SETTING_EDIT_FILE_NEW    32794
#define ID_PIN_SETTING_EDIT_FILE_OPEN   32795
#define ID_PIN_SETTING_EDIT_FILE_SAVE   32796
#define ID_PIN_SETTING_EDIT_FILE_SAVE_EXIT 32797
#define ID_NEW_PLANCONFIGFILE           32798
#define ID_DATA_BACKUP                  32799
#define ID_DATA_TEST                    32800
#define ID_POWERSETTING_POWERSSETTING   32801
#define ID_POWERSETTING_POWERSSAFE      32802
#define ID_POWERSETTING_SIGNPARAM       32803
#define ID_TOOLS_LOAD_TESTCASE          32804
#define ID_FILE_NEW32805                32805
#define ID_FILE_SAVE32806               32806
#define ID_FILE_SAVEEXIT                32807
#define ID_KI32808                      32808
#define ID_H32809                       32809
#define ID_TestConnectSystem            32810
#define ID_FILE_THO32811                32811
#define ID_FILE_EXIT                    32812
#define ID_CH32813                      32813
#define ID_EXIT                         32814
#define ID_TEST_ONBOARD                 32815

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        374
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1270
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
